export { default as Header } from "./Header"
export { default as Hero } from "./Hero"
export { default as WhyTalo } from "./WhyTalo"
export { default as Features } from "./Features"
export { default as WhyEmployers } from "./WhyEmployers"
export { default as JoinTalo } from "./JoinTalo"
export { default as Footer } from "./Footer"
// export { default as Test } from "./Test"
